version: "3.4"

services:

  mssql_image:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "noPassword@247"
      ACCEPT_EULA: "Y"
    ports:
      - "3200:1433"
    

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/Api/bin/
      - /app/Application/bin/
      - /app/Domain/bin/
      - /app/Infrastructure/bin/
      - /app/Persistence/bin/
      - /app/Api/obj/
      - /app/Application/obj/
      - /app/Domain/obj/
      - /app/Infrastructure/obj/
      - /app/Persistence/obj/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=server=mssql_image;Database=recharge-Db;user id=sa;password=noPassword@247;MultipleActiveResultSets=True
    depends_on:
      - mssql_image
    ports:
      - "5000:5000"



