version: "3.4"

services:

  nginx:
    restart: always
    image: ecoafrica/nginx_dev
    ports:
      - "80:80"

  frontend:
    image: ecoafrica/frontend_dev

  backend:
    image: ecoafrica/backend_dev
    environment:
      - DefaultConnection=Data Source=StagingDb.db
      - ASPNETCORE_ENVIRONMENT=Staging